### ISSUE TITLE
while file name contains ' ' space character, tempo is not working

### ISSUE THREAD

**Issue by erkantaylan** [alda-lang/alda#214] opened 2016-03-16 13:25 UTC
https://gist.github.com/erkantaylan/3a0b50fd0628ee8a671a
i have a file like that, i change tempo and nothing happens, may be decreasing tempo
but i write (tempo! 10000) tempo still like 40 or less
windows 10

**Comment by erkantaylan** [comment] 2016-03-16 13:29
https://gist.github.com/erkantaylan/3a0b50fd0628ee8a671a
i have a file like that, i change tempo and nothing happens, may be decreasing tempo
but i write (tempo! 10000) tempo still like 40 or less
windows 10

**Comment by daveyarwood** [comment] 2016-03-16 13:36
Thanks for reporting. I think this must be a Windows-specific issue, as I was able to change the tempo with this same file, saved with the same filename `nokia intro.alda` on OS X. This worked for me both in the Alda REPL and via the command-line client.

A couple questions:

1. Are you running into this problem when using the Alda REPL, or the command line client?
2. When you change the tempo, are you saving the file before you play it again?
3. If you rename the file to `nokiaintro.alda` (remove the space), does the tempo change work?

**Comment by erkantaylan** [comment] 2016-03-16 13:47
I dont know what happend but it works after typing commend line "alda repl" I changed nothing even name of the file and runned on commend line again not repl. 
i m running on commend line "alda play --file" ... (i use sublime build actually)
i have deal with 3-4 days to solve this issue thanks.

**Comment by elyisgreat** [comment] 2016-03-16 13:52
Can confirm not an issue for OS X. Seems to work for me in both command line and REPL. An interesting quirk with white space files that I've found, though, is that in the command line the spaces have to be escaped with `\` while in the REPL they cannot be escaped.

**Comment by daveyarwood** [comment] 2016-03-16 13:59
OK - glad the problem is fixed, whatever it was :)  Closing this for now.

**Closed by daveyarwood** 2016-03-16 13:59 UTC
