### ISSUE TITLE
Server trips up / opens multiple instances on occasion when playing songs

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#258] opened 2016-08-23 19:31 UTC
I've noticed with the new server that, on occasion, the server trips up when playing songs.

This is the error message I was getting:

```
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda play --file /Users/elygolden/Library/Mobile\ Documents/iCloud\~com\~gogolith\~gocoed/Documents/Alda\ Projects/Mario\ RPG\ Mushroom\ Kingdom\ Minor\ Cover.alda 
[27713] ERROR Alda server is down. To start the server, run `alda up`.
Elys-Computer-Mac-OS-Edition:~ elygolden$ 
```

even though the server is definitely *not* down... and then the song would proceed to play overlapping, creating a really trippy sound...

also, `alda restart` is pretty much never restarting the server, or it restarts but still claims that the server is down.

```
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda restart
[27713] Stopping Alda server...
[27713] Server down ✓

[27713] Starting Alda server...
[27713] Server down ✗
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda restart
[27713] Server already down.

[27713] Starting Alda server...
[27713] Server down ✗
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda version
Client version: 1.0.0-rc33

Server version:
[27713] 1.0.0-rc33
```

What is going on?

**Comment by elyisgreat** [comment] 2016-08-23 19:35
EDIT: I think I figured out part of the problem... when I ran `ps aux | grep alda` as a debug assistant for #234 , it told me that a lot of instances of the server were open...

```
elygolden       21268   2.9 13.9  6101384 1164540 s000  S     3:32pm   1:17.59 /usr/bin/java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host tcp://localhost --port 27713 --alda-fingerprint server
elygolden       20472   2.6  1.2  6098788  97972   ??  S     2:52pm   3:06.26 /usr/bin/java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host tcp://localhost --port 27713 --alda-fingerprint server
elygolden       21227   2.6  1.6  6111300 138060 s000  R     3:30pm   1:30.76 /usr/bin/java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host tcp://localhost --port 27713 --alda-fingerprint server
elygolden       20660   2.5  1.2  6104900  98780   ??  R     3:01pm   3:03.23 /usr/bin/java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host tcp://localhost --port 27713 --alda-fingerprint server
elygolden       21169   2.5  1.2  6111796 104048 s000  R     3:27pm   1:57.38 /usr/bin/java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host tcp://localhost --port 27713 --alda-fingerprint server
elygolden       20987   2.5  1.2  6106144 100236   ??  R     3:20pm   2:00.56 /usr/bin/java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host tcp://localhost --port 27713 --alda-fingerprint server
elygolden       21294   0.3  0.0  2453272    820 s000  S+    3:34pm   0:00.01 grep alda
```

Not quite sure why this is happening.

**Comment by daveyarwood** [comment] 2016-08-23 20:14
I think what's happening here is that it's taking a long time for the server to start and the client is timing out after 15 seconds. That's why it's saying "Starting Alda server..." and then "Server down"

```
[27713] Starting Alda server...
[27713] Server down ✗
```

So if you run `alda start` or `alda restart` after that, you will actually be starting a new server while the first server is still starting, and you end up with multiple servers running. This is buggy behavior for sure, and we should fix it. I'm just not sure what the best approach is.

I have a few ideas of how to improve this:

- We can make the default timeout period longer. I think it may have been 30 or even 60 seconds before, and I incorrectly assumed we could lower it to 15 as I was rewriting the client/server to use ZeroMQ. We should probably make it at least 30 seconds. I'm not really sure what a good default value should be, thoughts?
- We can add an option to make the timeout period longer, for those of us with slower computers. If you know it takes your machine longer than the default number of seconds to start a server, then you could use a longer timeout by running something like `alda --timeout 120 up` and the client would wait longer before giving up and assuming the server is down.
- When starting or restarting a server, we can have the client check `ps` output to see if there is already a server process running (or trying to start) on that port.

**Comment by daveyarwood** [comment] 2016-08-23 20:14
(BTW, these ideas are not mutually exclusive. We can, and probably should, implement all three.)

**Comment by daveyarwood** [comment] 2016-08-23 21:17
Looks like 30 seconds was what the timeout was before 1.0.0-rc32, FWIW.

**Comment by daveyarwood** [comment] 2016-08-23 22:20
I've got a new release on the way that I think will solve this issue.

**Comment by daveyarwood** [comment] 2016-08-23 22:41
@elyisgreat Give [1.0.0-rc34](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc34) a try and see what you think.

BTW, if you need to clean up those extra servers, you can run `kill -9 123 456 789`, replacing the `123`, `234`, etc. with the pid of each process you want to kill (the first number on each row when you do `ps aux | grep alda-fingerprint`). My hope is that you won't have to reach for `ps` and `kill` in the future when using Alda!

**Comment by elyisgreat** [comment] 2016-08-23 22:47
`alda status` is very useful. previously I would have to run a server command to check status (usually `alda version`).

Seems like the problem is mostly cleared up. after a few server restarts it seems like the file is only playing once, and only one server is showing up in the process list. 

I'm also getting almost no false positives when restarting.

**Comment by daveyarwood** [comment] 2016-08-23 22:52
Can you describe more what it sounds like when it "plays duplicate"? Does it sound like more than one server is playing the same score at the same time?

**Comment by elyisgreat** [comment] 2016-08-23 23:05
it sounds like the same score being played in a round (otherwise I wouldn't be able to tell)

**Comment by daveyarwood** [comment] 2016-08-24 00:10
And this is with only one server process running?

**Comment by elyisgreat** [comment] 2016-08-24 00:10
I believe so

**Comment by daveyarwood** [comment] 2016-08-24 00:37
Hmm... I think I see what the problem is.

I've already mentioned the "server start timeout" where, when you're starting a server with `alda up`, the client will stop waiting after 30 (or 15, pre-1.0.0-rc34) seconds and report that the server is down.

There is another timeout for how long the client will wait for a response from the server after you give it a command, e.g. `alda play -f somefile.alda`. The timeout is currently hard-coded at 2500ms, and each time if it doesn't get a response within that timeframe, it will retry up to 3 more times. This is usually a decent pattern to help ensure you get a response, but now that I think about it, it's not a great one for us, because we want the request to be sent exactly once, so we hear the playback exactly once.

I'll have to read up more on good patterns to use with ZeroMQ, and see if I can come up with a better solution to what we have now... we need a good way to handle the case that you play a large score that takes > 2500 ms to process.

**Comment by daveyarwood** [comment] 2016-08-24 14:54
I have some ideas for how to solve this in a nice way.

So here's the way it works now:

- Client sends a request (e.g. "play this score") to the server. Client expects a response within 2500 ms, or it will assume the request got lost and send it again.
- The server starts processing the request, and it may or may not take less than 2500 ms to do so. Processing the request is a pipeline that includes A) parsing the Alda code, B) evaluating the parsed Alda code to determine what the sound engine needs to do, and C) using the sound engine to play the score.
- If the client doesn't get a request in under 2500 ms, it sends the request again.
- The server is still processing the first request, and starts processing the second one too.
- The first request makes it through the pipeline and the score starts playing, then the second request makes it through the pipeline and starts playing too.

My idea for how to improve this experience:

- The end-user experience is the same -- you make a request to the server, e.g. "play this file," Alda takes care of it for you, and eventually (depending on the size of the score) you hear the playback.
- Instead of waiting for the whole pipeline to complete before reporting back to you, the server finds an available worker and responds immediately to let the client know the request was received and the port of the worker who is handling it so the client can talk directly to the worker now.
- Behind the scenes, the client makes a series of small requests for you, checking in on where the worker is in the pipeline and giving you updates as they happen like "Parsing..." and "Evaluating..."
- When the worker is done, you'll see "Playing..." and you'll hear the score.
- The client will not send duplicate requests unless the worker is unresponsive after a reasonable timeout and it needs to start over. We can use reasonable timeouts based on where we are in the pipeline. For example, receiving the initial request should happen immediately, whereas we can expect to wait for up to ~5 seconds each for parsing and evaluating (although we can poll every 250 ms or so, so we get updates faster).

If this sounds complicated, it's because it is! IPC is inherently complicated. The good news is that all the complexity will be behind the scenes, so the user will never have to worry about things like worker processes. The user will just use the Alda CLI client like normal and it will "just work," and the client will be able to know more about what the server is doing, which ought to make the Alda end user experience less confusing/unreliable.

I think I'd like to get the server/worker architecture working first (being discussed in #243), then work on this "pipeline reporting" idea and having the client use smarter timeouts based on where a request is in the pipeline.

**Comment by daveyarwood** [comment] 2016-09-04 20:07
Fixed in [1.0.0-rc35](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc35). (Take care to read the "TL;DR" at the top of the changelog before updating!)

Please feel free to re-open if you're still seeing the same issue after updating, or you can always open a new issue.

I ended up not needing to implement the "worker status pipeline" to fix the immediate issue. I still like the idea, though, so I will open that as a separate issue.

**Closed by daveyarwood** 2016-09-04 20:07 UTC
Labels: bug, in progress

**Comment by daveyarwood** [comment] 2016-09-04 20:14
To be totally clear -- the `alda play` command currently does not retry at all, and instead, it has a fixed timeout of 3 seconds. If it takes longer than 3 seconds to get a response (e.g. when playing a large score), it will conclude that the server is "down" and exit. However, behind the scenes, the request is still going through, so you should hear the audio once the score starts playing.

This is not ideal, and I think the solution will be the worker status pipeline.

**Comment by elyisgreat** [comment] 2016-09-04 21:15
Wow. Seems to finally be fixed. I have noticed, however, in place of this issue, the timing is choppier when previously this issue would have happened.

**Comment by daveyarwood** [comment] 2016-09-04 21:47
I would guess that it's performance related. Using less workers (like 1 or 2) should help.

**Comment by elyisgreat** [comment] 2016-09-17 02:16
I'm still sometimes getting this
![alda restart screenshot](https://cloud.githubusercontent.com/assets/8622264/18605272/1deb0f6e-7c5b-11e6-9839-9abec525a4cd.png)
when I restart. Not sure where it's addressed but it's confirmed for 1.0.0rc38

**Comment by daveyarwood** [comment] 2016-09-17 13:02
Alright -- so it seems like the issue is that when starting a server, the server is not confirmed to be up within the client's timeout, which by default is 30 seconds. Is it taking at least 30 seconds for you to get the "Server down" message?

Does increasing the timeout help? i.e.:

```
alda --timeout 120 up
```

**Comment by elyisgreat** [comment] 2016-09-17 20:00
Seems to, however I haven't done thorough testing yet.
