### ISSUE TITLE
Pause/Stop function in commands and REPL

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#209] opened 2016-03-13 00:52 UTC
Right now, it can be really annoying to play a song, only to realize you didn't want to listen to the whole thing. Currently, the only way to stop a song from playing is to kill the REPL, or, when playing via `alda play`, to kill the `coreaudiod` process. When songs load and play [very slowly](https://github.com/alda-lang/alda/issues/208) it's really annoying to reload the REPL. It would be beneficial to have `:stop` and `:pause` commands, as well as `alda stop`. 

Thoughts?

**Comment by daveyarwood** [comment] 2016-03-13 00:56
Duplicate of #69 :)

**Closed by daveyarwood** 2016-03-13 00:56 UTC

**Comment by elyisgreat** [comment] 2016-03-13 00:57
Sorry. I don't think they mention anything about non-REPL commands though. I'll change the title.

**Comment by daveyarwood** [comment] 2016-03-13 00:58
We can track both ideas (`alda stop` in the client vs. `:stop` in the REPL) in #69. I'd like to keep the REPL experience vs. the CLI experience as similar as possible.

**Comment by elyisgreat** [comment] 2016-03-13 00:59
I think that's a good idea. #69 isn't my issue though so I can't change the title.

**Comment by daveyarwood** [comment] 2016-03-13 00:59
Oh, good call. I'll change it :)
