### ISSUE TITLE
Allow tying notes across barlines

### ISSUE THREAD

**Issue by july2993** [alda-lang/alda#97] opened 2015-09-19 10:53 UTC
piano: g4|~8
this is valid using alda repl
but when write it in a file and use alda play --file  file.alda will parse error

```
Parse error at line 1, column 12:
piano: g4~|8
           ^
Expected one of:
#"[a-zA-Z]{2}[\w\-+'()]*"
"|"
"@"
"%"
"("
"<"
">"
"o"
"r"
"V"
"#"
"(*"
#"\s"
#"[a-g][+-]*"```

**Comment by crisptrutski** [comment] 2015-09-19 13:28
@july2993 I strongly suspect that expression became unparsable during #95, that your REPL was opened before the release, and alda automatically updated before playing the file you created.

Note that the note durations idiomatically appear as suffixes to notes, ie you'd write 'g4~a8` rather than `g4~8a`, in fact I had not realised that `g4~8` would even parse. If you keep away from "orphan durations" in your score you shouldn't have issues about where bar lines are placed.

@daveyarwood perhaps you could clarify whether these kinds of expression should be defined, then we can make them consistently parse or not parse, regardless of bar lines :smile:

**Comment by july2993** [comment] 2015-09-19 14:03
@crisptrutski  Yes, i restart REPL and parse fail now. 

Not so understanding what you said, i know little about music theory, will try to learn more and play alda, thanks you help anyway.

**Comment by crisptrutski** [comment] 2015-09-19 14:11
Sorry that my response wasn't clear - to try another phrasing "put durations after notes, not before"

Closing this issue, but don't stop playing or asking questions :smile:

**Comment by daveyarwood** [comment] 2015-09-19 16:11
Whoops - I definitely introduced a regression with #95 - actually, looking at it more positively, it's forcing us to confront the problem of tying a note across a bar. :)

Tying notes together is an important feature of the language -- you can add note durations together, like:

    c1~1~1~1~2.

(a C "whole note + whole note + whole note + whole note + dotted half note)

You used to be able to tie notes across barlines, because barlines were just ignored by the parser. So doing something like this was perfectly acceptable:

    c1|~1|~1|~1|~2.

or

    c1~|1~|1~|1~|2.

Both of those worked prior to #95 because they boil down to `c1~1~1~1~2.` with the barlines stripped out.

When I made barlines significant in #95, it effectively made it so that bar lines "interrupt" ties between notes., so the next thing after a bar line has to be a pitch name because something like `8` is not a valid note by itself.

I think it will be important that we be able to inject barlines inside of tied notes, as we move toward being able to export Alda to visual sheet music via MusicXML and/or LilyPond, so I'll leave this issue open for now.

I've got a few hours free, maybe I can hack in a way to make this syntax legal :+1:

**Closed** 2015-09-19 17:54 UTC
Labels: bug

**Comment by daveyarwood** [comment] 2015-09-19 17:55
@july2993 This issue should now be fixed -- you can now tie notes across barlines :+1:
