### ISSUE TITLE
alda restart command error

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#241] opened 2016-06-20 04:00 UTC
when running the `alda restart` command, I get this dialog:

```
[27713] Stopping Alda server...
[27713] Server down ✓

[27713] Starting Alda server...
[27713] Server down ✗
```

Yet, the server starts up just fine.

**Comment by daveyarwood** [comment] 2016-06-20 04:13
When you start (or restart) a server, this is what happens:

1. The `alda` client starts a server process in the background.
2. The client checks every 500 ms to see if the server is up yet.
3. Once the server is up, it says "Server up ✓" and exits.

The client is set to time out after 30 seconds, so if it's been 30 seconds and the server still isn't up, it will report "Server down ✗" and exit. This is to keep the start/restart command from waiting forever for a server to start up, in case there is some problem. Of course, it is always possible that a server will take more than 30 seconds to start up -- maybe if it's running on an overloaded or otherwise slow system. In the event that this happens, you will see "Server down ✗" but then the server will still start up.

(The client will also report "Server down ✗" immediately if there is some unknown exception when trying to ask the server if it's up yet -- this should be rare.)

When you got "Server down ✗" there, did it take 30 seconds before it reported "Server down ✗", or was it more immediate? Also, when you say the server starts up just fine, what do you mean exactly?

**Comment by elyisgreat** [comment] 2016-06-20 04:21
I didn't notice it before, but yes. When I said "starts up fine" I meant this: When I ran an `alda play` command to see what would happen, it did not give me the "starting alda server" dialogue it normally would give in the event that the server was actually down. It just played the song.

By the way, when I run an alda play command when the server is actually down, I get this dialogue:

```
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda play --file /Users/elygolden/Library/Mobile\ Documents/iCloud\~com\~gogolith\~gocoed/Documents/Alda\ Projects/We\ are\ the\ Crystal\ Gems\ Choir\ Arrangement\ copy.alda 
[27713] Starting Alda server...
[27713] Server down ✗
Exception in thread "main" java.util.UnknownFormatConversionException: Conversion = '1'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.io.PrintStream.format(PrintStream.java:970)
	at java.io.PrintStream.printf(PrintStream.java:871)
	at alda.AldaServer.msg(AldaServer.java:113)
	at alda.AldaServer.error(AldaServer.java:118)
	at alda.Client.main(Client.java:545)
```

When I run the same command after the previous dialogue, the song plays normally.

```
Exception in thread "main" java.util.UnknownFormatConversionException: Conversion = '1'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.io.PrintStream.format(PrintStream.java:970)
	at java.io.PrintStream.printf(PrintStream.java:871)
	at alda.AldaServer.msg(AldaServer.java:113)
	at alda.AldaServer.error(AldaServer.java:118)
	at alda.Client.main(Client.java:545)
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda play --file /Users/elygolden/Library/Mobile\ Documents/iCloud\~com\~gogolith\~gocoed/Documents/Alda\ Projects/We\ are\ the\ Crystal\ Gems\ Choir\ Arrangement\ copy.alda 
[27713] Playing file...
Elys-Computer-Mac-OS-Edition:~ elygolden$ 
```

**Comment by daveyarwood** [comment] 2016-06-20 13:45
Hmm... it looks like what's happening there is that the Alda client is catching an error and trying to print it, but something is off with the error message (maybe it contains format characters like `%s`?) and the `printf` part is failing, so we can't see what the error is.

Java is not my strong suit... I'm going to open a separate issue for that and see if someone better at Java has a solution :)

I'm not able to reproduce the issue with slow (> 30s) server startup time, but I wonder if there is a better way we should be handling this. The solution might be as simple as increasing the polling timeout to something like 60 seconds, or maybe there is a better solution that I'm not thinking of.

**Comment by elyisgreat** [comment] 2016-06-20 15:39
seems to be working normally in 1.0.0rc20...

**Comment by daveyarwood** [comment] 2016-06-20 15:47
OK, well that's good, at least :)

I'm going to close this for now, but please feel free to reopen if you run into this problem again.

**Closed by daveyarwood** 2016-06-20 15:47 UTC
Labels: bug, low-hanging fruit, up for grabs
