### ISSUE TITLE
Cramming while in a voice causes an exception

### ISSUE THREAD

**Issue by jgkamat** [alda-lang/alda#184] opened 2016-02-12 17:34 UTC
For example: `piano: V1: o5 {c < b a g}1 | e1     V2: o4 c1/e/g | < g+/b` in the alda repl results in:

```
                                                              alda.Client.main      Client.java:  314
                                                     alda.AldaServer.startRepl  AldaServer.java:  400
                                                       alda.Util.callClojureFn        Util.java:  197
                                                                           ...                       
                                                         alda.repl/start-repl!         repl.clj:   37
                                                         alda.repl/start-repl!         repl.clj:   49
                                                      alda.repl/start-repl!/fn         repl.clj:   58
                                                   alda.repl/start-repl!/fn/fn         repl.clj:   73
                                                     alda.repl.core/interpret!         core.clj:   50
                                                             clojure.core/eval         core.clj: 3105
                                                                           ...                       
                                                 clojure.core$eval10182.invoke   NO_SOURCE_FILE      
                                           clojure.core$eval10182.invokeStatic   NO_SOURCE_FILE      
                                                            clojure.core/apply         core.clj:  648
                                                                           ...                       
                    clojure.core$eval10182$iter__10183__10187$fn__10188.invoke   NO_SOURCE_FILE      
          clojure.core$eval10182$iter__10183__10187$fn__10188$fn__10901.invoke   NO_SOURCE_FILE      
                                                            clojure.core/swap!         core.clj: 2260
                                                                           ...                       
clojure.core$eval10182$iter__10183__10187$fn__10188$fn__10901$fn__10904.invoke   NO_SOURCE_FILE      
                                                              clojure.core/vec         core.clj:  377
                                                                           ...                       
                                                           clojure.core/map/fn         core.clj: 2644
                                                            clojure.core/first         core.clj:   55
                                                                           ...                       
java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Long
```

I'm using ` alda v1.0.0-rc6`

I'm using a custom sound-font, but I don't think that's the problem? I'll try it again with the defaults if you suspect that's the problem. Thanks again for making this project! =)

**Comment by daveyarwood** [comment] 2016-02-12 17:55
Thanks for reporting this! I am able to reproduce both in the REPL and via the client.

It shouldn't be a problem with your soundfont... I suspect this is a bug. Digging deeper...

**Comment by daveyarwood** [comment] 2016-02-12 18:45
Yep, it's definitely a bug. I've got a fix on the way.

Basically, each `voice` must return a list of events (i.e. notes). The voice group (`voices`) collects these lists of events into a map of each voice's number to its events. The only reason we do this is as a convenience to Clojure programmers who want to use Alda as a library.

Technically, each "event" (like a note, rest, etc.) is really a list of events -- one for each instrument currently playing. For instance, if you evaluate `(note (pitch :c))` you will get as a result a list of C notes, one for each currently active instrument.

So the problem is, when we implemented the cram expression event type, we forgot to have it return anything sensible, as most of the time, nothing outside of the cram expression cares about its return value, just the side effects. Trouble is, `voice` does care -- it's expecting a list of events.

As an immediate fix, I'm adjusting cram expressions so that they return the list of "crammed" events they contain.

Thinking more big picture, this part of the codebase is needlessly complex, mostly because it relies heavily on side effecting functions and mutable state. I'm actually working on "functionally purifying" alda.lisp (#153) so that it will be a lot easier to work with and understand, and so that we can prevent more of these types of bugs before they happen.

**Comment by daveyarwood** [comment] 2016-02-12 18:57
Fixed in [1.0.0-rc7](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc7).

**Closed by daveyarwood** 2016-02-12 18:57 UTC

**Comment by jgkamat** [comment] 2016-02-12 19:08
Nice, thanks for the quick fix! I don't know the internals of alda yet, so I don't think I can help too much, but I'm thinking about contributing in the future. :smile:

**Comment by daveyarwood** [comment] 2016-02-12 19:12
That would be awesome! Once I make these changes I'm working on in #153, I think the code will make a lot more sense. Currently we're doing some pretty crazy things with macros and using side effects a lot more than we should. :blush:
