### ISSUE TITLE
weird quantization volume bug

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#229] opened 2016-05-26 13:22 UTC
So, I was messing around with some of my alda code, and I came a cross this bizarre bug.

```
midi-synth-voice:

V1: (quant 90)(vol 200/3) 
V2: (quant 90)(vol 700/8) 
V3: (quant 90)(vol 200/3) 
V4: (quant 90)(vol 200/3) 

V2: o5 r2 c6 d c < b2 f+4. g1 e8 g4 a > c d8 e8~2 c6 d c < b2 f+4. g1 e8 g4 a4 g4 f8 e8~2
V2: > c6 d c < b2 f+4. g1 e8 g4 a > c d8 e8~2 c6 d c< b2 f+4. g2.. e4g8 a4 g8 f+4 g e2.. e8
V1: [o4 (quant 50) (comment "doesn't seem to be as audible as in 1.0.0rc16") c4 e g r (quant 90) f+1 b b2 a]*2 (quant 50) c4 e g r (quant 90) f+1. > (vol 700/8) c2 b a (vol 200/3) e1 e- e e2 f+ e1
V3: [o4 e1 a g g2 f]*2 o4 e1 a b r1 (quant 50) c4 e g r (quant 90) a1 g g2 a b1
V4: [o4 c1 < b > e e2 d]*3 c1 < b > e e2 f+ a-1
```

~~When playing this in the REPL of 1.0.0rc16, it plays as I expect. However, if I play it outside the REPL, the volumes are all out of whack, and the contents of the V1 voice becomes inaudible. And in 1.0.0rc17, it sounds out of whack both in the REPL and out of it.~~

UPDATE: It plays just fine in 1.0.0rc16 both in the REPL and out; I just forgot to restart the server. Only in 1.0.0rc17 does it play weirdly.

I haven't been able to break this down further into more readable code snippets; each voice sounds fine on its own. What's going on here?

**Comment by daveyarwood** [comment] 2016-05-27 01:46
I took a close look at/listen to this score and I think I see what's going on.

You have 4 voices, V1-4. V2 is a bit louder than the others (700/8 == 87.5, 200/3 == 66.6667), so it seems like you're intending V2 to be the "melody" voice. At the point in your score where you put the comment that it doesn't seem to be as audible before, it's in a voice (V1) that's softer in volume than V2.

The change between 1.0.0-rc16 and 1.0.0-rc17 has to do with how the sound engine handles multiple MIDI notes that are the same note (e.g. middle C), playing at the same time -- specifically, it makes sure that one note's MIDI "note off" event won't get triggered if the other note should still be playing. So, I don't think it would affect volume between voices of one instrument... not sure what the connection might be there.

This is a beautiful score, by the way! I'd love to hear more.

**Comment by elyisgreat** [comment] 2016-05-27 01:55
Interesting... I still don't understand the source of the difference. The volume being louder for V2 is intentional; I just don't get why I'm hearing V1 in 1.0.0rc16 and barely at all in 1.0.0rc17. 

By the way, if you'd like to hear the whole thing, I've attached it [here](https://github.com/alda-lang/alda/files/285644/We.are.the.Crystal.Gems.Choir.Arrangement.alda.zip). It's a cover of the Steven Universe theme, arranged for vocals. The reason I've included this section is it's where the bug is most aurally prominent between the two versions.

**Comment by daveyarwood** [comment] 2016-05-27 02:18
Wow, this is great! I've heard good things about Steven Universe and its music, but haven't heard any of it until now. I'm gonna have to check more of it out.

I'm not sure if there is an Alda bug here or not... General MIDI can sometimes sound weird, volume-wise, when working with multiple voices, and it can vary depending on the instrument. I tried the snipped in your original post with `piano` as the instrument and then `midi-synth-voice`, and it did sound like V1 was a little more buried in the mix with the synth-voice vs. the piano. I would guess that it's something to do with the sonic quality of the samples used for each instrument in the MIDI soundfont. Especially with the piano though, it doesn't sound to me like there is an obvious bug in this version of Alda. Each voice does appear to be at an appropriate volume.

One thing you could try is panning the voices to help make them sound more distinct. You could use panning values like 20, 40, 60 and 80 to get an even distribution across your speakers. If there is a bug to be found here, that might help bring it out in a clearer way.

Another thing that might be interesting to try would be to use separate instrument instances instead of a single instrument with multiple voices. The difference here is that each voice part would be on its own MIDI channel, instead of sharing one channel. I'd be curious to know if that makes any difference in what you can hear. So for example, instead of doing this:

```
midi-synth-voice:
  V1: c d e
  V2: e f g
  V3: g a b

  V1: f g a
  V2: a b > c
  V3: > c d e
```

You would do:

```
midi-synth-voice "voice1": c d e
midi-synth-voice "voice2": c d e
midi-synth-voice "voice2": c d e

voice1: f g a
voice2: a b > c
voice3: > c d e
```

**Comment by elyisgreat** [comment] 2016-05-27 02:30
it actually sounds even more messed up. Give this a listen:

```
midi-synth-voice:
midi-synth-voice "vo1": (quant 90)(vol 200/3) 
midi-synth-voice "vo2": (quant 90)(vol 700/8) 
midi-synth-voice "vo3": (quant 90)(vol 200/3) 
midi-synth-voice "vo4": (quant 90)(vol 200/3) 

vo2: o5 r2 c6 d c < b2 f+4. g1 e8 g4 a > c d8 e8~2 c6 d c < b2 f+4. g1 e8 g4 a4 g4 f8 e8~2
vo2: > c6 d c < b2 f+4. g1 e8 g4 a > c d8 e8~2 c6 d c< b2 f+4. g2.. e4g8 a4 g8 f+4 g e2.. e8
vo1: [o4 (quant 50) (comment "doesn't seem to be as audible as in 1.0.0rc16") c4 e g r (quant 90) f+1 b b2 a]*2 (quant 50) c4 e g r (quant 90) f+1. > (vol 700/8) c2 b a (vol 200/3) e1 e- e e2 f+ e1
vo3: [o4 e1 a g g2 f]*2 o4 e1 a b r1 (quant 50) c4 e g r (quant 90) a1 g g2 a b1
vo4: [o4 c1 < b > e e2 d]*3 c1 < b > e e2 f+ a-1
```

**Comment by daveyarwood** [comment] 2016-05-28 21:31
Heh... that does sound really messed up. I just realized yesterday that there was probably a bug related to 1.0.0-rc17 (see #231). I think this confirms the bug. Let me see if I can fix that real quick.

**Comment by daveyarwood** [comment] 2016-05-28 21:51
1.0.0-rc18 fixes that issue. Both versions of your score (separate voices vs. separate instruments) sound the same to me.

**Comment by elyisgreat** [comment] 2016-05-28 22:17
excellent! I will be testing shortly, however I'm having a little problem with the server. 


It's not restarting
![server not restarting](https://cloud.githubusercontent.com/assets/8622264/15630253/4e1e82b8-2500-11e6-94ee-13ad4e19397b.png)

Like, at all
![server still not restarting](https://cloud.githubusercontent.com/assets/8622264/15630255/59d4fcb8-2500-11e6-807e-1791b46d907f.png)

**Comment by daveyarwood** [comment] 2016-05-28 22:20
Hmm... that's strange. I'm not sure what could be causing that. So, after it says `[27713] Stopping Alda server...` does it just hang? Is there an error message?

**Comment by elyisgreat** [comment] 2016-05-28 22:35
When I restart my computer it actually informs me that the server is down.

![server down](https://cloud.githubusercontent.com/assets/8622264/15630300/d74528b0-2502-11e6-831f-9b38b7686e45.png)

So what appears to be happening is that on occasion, the `alda restart` command is shutting down the server, but not registering it. So whenever I run the `alda restart` command, it just gets stuck here.

**Comment by daveyarwood** [comment] 2016-05-28 22:44
What's shown in that screenshot is the expected behavior -- when you restart your computer, it stops whatever processes you have running, including Alda servers. When the OS comes back up, you have to start an Alda server again in order to use Alda. In the future, we may look into ways to have it always running by default, but for now this is what we have to deal with :)

In the past, I did notice some weirdness around servers on older versions not stopping when a client with a newer version tells them to, but I haven't seen any issues with that lately. It's entirely possible that there is a bug here, but so far, I haven't been able to pinpoint it. ¯\\\_(ツ)\_/¯

On 1.0.0-rc18, is the original issue you were seeing still there?

**Comment by elyisgreat** [comment] 2016-05-28 22:51
the midi issue is fixed. the server thing I am taking to another issue. As for the original issue, it still doesn't quite sound the same as the original score in 1.0.0rc16.

**Comment by daveyarwood** [comment] 2016-05-28 23:33
OK, I think I may have figured out what's going on now. I downloaded 1.0.0-rc16 and used it to start a 1.0.0-rc16 server on a different port, so I could compare it back-to-back vs. the 1.0.0-rc18 server I already have running on port 27713.

They do sound different -- here's why.

At the point in the score where it sounds different, there are two voices (V1 and V4) that both play a middle C at the same time, but V4 plays it for longer.

As of version 1.0.0-rc16, there was a bug (related to #27) where in situations like this where two voices are playing the same note at the same time, the MIDI "note off" event at the end of the first note will cut off the second note as well, even if it's not done playing yet. So when V1 plays a middle C and cuts it off after 1 beat, the V4 that's also playing a middle C gets cut off before the note (which should last 4 beats) is done playing. As a result, it becomes easier to hear V1 because V4 isn't in the mix anymore.

Version 1.0.0-rc17 fixed that issue, so starting from that version, V4 does not get cut off before it's supposed to, so one consequence of this is that it's harder to hear V1 because it's just as loud as V4 and playing in the same range.

I think things are working the way they're supposed to now. If you'd like to hear V1 come out of the mix a little more, I would either increase its volume, or maybe decrease V4's volume.

**Comment by elyisgreat** [comment] 2016-05-28 23:53
I think you're right; There still seems to be *slight* discrepancies even when I mute V4, though (using `midi-square-lead` makes it easier to hear the differences). 

To what should I change the volumes to bring back the 1.0.0rc16 sound?

**Comment by daveyarwood** [comment] 2016-05-29 00:05
It looks like, prior to the fix in 1.0.0-rc17, V1 was also interfering with the first E whole note in V3, so that by the time you get to beat 3 of the score, the whole notes in both V3 and V4 have been cut off early, so V1 and V2 are all you hear.

What I would do is have V1 almost as loud as V2, to bring out that `c4 e g` arpeggio a bit more. I'm not quite sure what your system is with the volume fractions, but if 200/3 is about 67 and 700/8 is about 87, then perhaps you could try putting the volume of V2 somewhere around 80, and see how that sounds?

**Comment by elyisgreat** [comment] 2016-05-29 00:15
Not quite the same, but it's alright. I still think the original sounds ok.

>I'm not quite sure what your system is with the volume fractions

they're fractions of full volume. because volume is a percentage and not a fraction of the unit (1), I have to multiply the numerators by 100.

**Comment by daveyarwood** [comment] 2016-05-29 03:12
OK - glad we figured it out. I'm going to close this issue.

**Closed by daveyarwood** 2016-05-29 03:12 UTC
