### ISSUE TITLE
Error java.lang.UnsupportedClassVersionError: boot/App

### ISSUE THREAD

**Issue by sergiolch** [alda-lang/alda#71] opened 2015-09-09 17:18 UTC
I followed all steps and I did `alda relp` and got:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: boot/App : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

I just don't know what to do. I really wanted to see all features, looks an amazing program.

**Comment by sergiolch** [comment] 2015-09-09 17:19
I have osx 10.10.5

**Comment by daveyarwood** [comment] 2015-09-09 22:19
Hi,

This is due to Boot requiring JDK 1.7+; installing the [latest JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) should fix it.

(duplicate of #41)

**Closed by daveyarwood** 2015-09-09 22:19 UTC
