### ISSUE TITLE
export to midi?

### ISSUE THREAD

**Issue by Pomax** [alda-lang/alda#270] opened 2016-09-20 04:56 UTC
Kind of hacky, but I'm looking for a decent step sequencer with keyboard input (computer keyboard, good luck finding that through google) in the old "tracker" style for creating some nice arpeggiator riffs, and coming up with nothing.

However, there's alda! I can just program an arpeggio pattern in seconds, and if that could be exported to a .mid file, I can import that into my DAW (Cakewalk Sonar pro) or even a fair number of VST instruments (like Z3TA+ 2), so.... I see midi import as a thing-to-do, but what about output? 

(unfortunately, Sonar has no MusicXML import capabilities, it only exports to it. No idea how that makes sense, but it's a thing).

**Comment by elyisgreat** [comment] 2016-09-20 05:05
I definitely want to see this in the near future. MIDI export is dealt with in #145, so I recommend bringing the discussion over there, as it hasn't seen a comment for 6 months...

**Comment by daveyarwood** [comment] 2016-09-20 13:04
I really like the idea of using Alda to program in sequencer patterns! The "piano roll" layout is always cumbersome to work with. I can imagine some sort of Alda DAW plugin that lets you type in Alda code and when you're done, it programs in the notes for you.

It definitely seems like being able to export to MIDI would be the first step towards that. Closing as duplicate of #145, please discuss there. I don't think this is something I can work on anytime soon, but it would be a great place for a potential contributor to dip their toes in the water.

BTW @Pomax , have you looked at [Sunvox](http://www.warmplace.ru/soft/sunvox/)? It has a tracker-style input for entering notes, and you can build synthesizer instruments by dragging cables between different generator and effects modules. It's super fun -- I've used it to create a couple of chiptune tracks: [1](https://soundcloud.com/daveyarwood/you-belong-to-me-chip-cover) [2](https://soundcloud.com/daveyarwood/badinerie-from-orchestral)

**Closed** 2016-09-20 13:04 UTC
Labels: duplicate

**Comment by Pomax** [comment] 2016-09-20 15:10
Oh man, if there was a DAW/VSTi module for Node.js, things would get *reaaaally* interesting. I haven't looked at Sunvox (it has Nokia n900 support? what?!), but I did look at reViSiT specifically to do the tracker work and sending that on to whatever synth(s) actually need(s) to play the patterns.
