### ISSUE TITLE
[27713] ERROR Read timed out

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#191] opened 2016-02-28 18:19 UTC
When playing longer alda scores using the `alda play` command, I sometimes get an error that says `[27713] ERROR Read timed out`. However the song still plays normally, and when I play shorter scores I get `[27713] Playing file...`. What's going on?

**Comment by jgkamat** [comment] 2016-02-28 18:33
This is a duplicate of #170
someone needs to debug it sooner or later, I've run into it too.

**Closed** 2016-02-29 00:04 UTC
Labels: duplicate
