### ISSUE TITLE
Volume increase on unison

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#200] opened 2016-03-09 03:54 UTC
EDIT: I also found an unexplained volume fluctuation in the `d4. d4. d4 d4. d4. d4` on the second line V3 in this code:

```
midi-synth-voice:
(vol! 200/3)
V1: (vol 200/3) o4 f+1 (quant 50) b-6 b- b- (quant 90) b-2 (quant 50) g4. g4. g4 g4. g4. g4 (quant 90)
V3: o4 d1 (quant 50) f+6 f+ f+ (quant 90) f+2 (quant 50) d4. d4. d4 d4. d4. d4 (quant 90)
V1: (vol 700/8) r4 a8 f+ a a a > e4 e8 d4 c+4. < a8 b a4 d d b a d e4.
V3: d2.. a4 a8 g4 f+4. r8 (quant 50) d4. d4. d4 d4. d4. d4 (quant 90)
```
this persists even when removing the global attribute. I'm not sure what it's coming from; it disappeared when isolating for V3.

EDIT: Wow am I silly. the note overlap of the two d's is causing it. Still an interesting phenomenon though.

**Comment by daveyarwood** [comment] 2016-03-09 13:51
Yeah, that is an interesting phenomenon. Two voices playing in unison produces a [chorus effect](https://en.wikipedia.org/wiki/Chorus_effect). I think this is intended behavior, so I will close this issue.

**Closed by daveyarwood** 2016-03-09 13:51 UTC

**Comment by elyisgreat** [comment] 2016-03-09 21:37
Interesting. How do you decide for which instruments to implement this and which not to implement this? Or is it a matter of the MIDI soundfont?

**Comment by daveyarwood** [comment] 2016-03-09 21:59
I think this is something the MIDI system does by default, so we have no control over it.

**Comment by elyisgreat** [comment] 2016-03-09 22:10
Ah. What instruments does it do it with? Is it even dependent on the soundfont?

**Comment by daveyarwood** [comment] 2016-03-09 23:09
It could be dependent on the soundfont. I would guess that it does it for all instruments. I've been working with General MIDI on computers for practically my whole life and I remember always hearing that chorus effect when voices played in unison.
