### ISSUE TITLE
Global attributes called at the same time from different instruments

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#283] opened 2016-11-08 22:41 UTC
I believe you mentioned this before, however I found some global attribute behaviour that is slightly unintuitive. Consider the code:

```
piano "pA": c4 d e f g
piano: "pB": r2 c4 d e
```

which plays in rhythm. However when I apply global attributes like so:

```
piano "pA": (tempo! 120) c4 (tempo! 240) d e f g
piano "pB": r2 c4 d e
```

The second piano lags behind. This is (as I believe you mentioned) because the second attribute call occurred at a point in the score before the second piano is finished its event, so it applies the speedup on the next event. Notice how the score below plays in rhythm:

```
piano "pA": (tempo! 120) c4 (tempo! 240) d e f g
piano "pB": r4 r c d e
```

I believe this is intended, however it may be unintuitive for people who don't understand the concept of discreet events, so I thought I could bring it up for discussion here.

**Comment by daveyarwood** [comment] 2016-11-08 22:52
Your explanation is spot-on. I think this is the "correct" behavior, but I'm open to improving our documentation if there is any way we can make this more intuitive.

**Comment by elyisgreat** [comment] 2016-11-08 23:02
The most intuitive would be to have it actually change for all instruments at the time it was called, however I'm not sure how that would be implemented (I think attributes, even global ones, are stored per event). 

Another weird thing I found when playing around with attributes is this:

```
piano "pA": (tempo! 120) c d e f g
piano "pB": (tempo! 240) e f g a b
```

This sets the same global attribute to two conflicting values at the same time (which shouldn't happen), but what actually happens is that it's treated as a local call. Again, unsure if intended.

**Comment by daveyarwood** [comment] 2016-11-08 23:08
> The most intuitive would be to have it actually change for all instruments at the time it was called, however I'm not sure how that would be implemented (I think attributes, even global ones, are stored per event).

I think agree with you to some extent... I think maybe I misspoke when I said this is the "correct" behavior. :)

I think what you're describing is the behavior many users might expect, but from an implementation perspective, I think it's doing what it makes sense for it to do. 

The length of a note is determined by the tempo at the time the note is played. So if the tempo is 120 when you start playing a half note, and the global tempo gets changed in the middle of the note, the half note you're playing is still going to last the same amount of time.

This might be slightly unintuitive, but I don't think it's difficult to understand if it's explained clearly in the docs. I think it would be very difficult to change this behavior because of the way note duration is calculated, and I think it makes more sense to document this clearly than to rewrite the whole duration calculation system just to make this change.

**Comment by daveyarwood** [comment] 2016-11-08 23:09
> Another weird thing I found when playing around with attributes is this:
>
> ```
> piano "pA": (tempo! 120) c d e f g
> piano "pB": (tempo! 240) e f g a b
> ```
>
> This sets the same global attribute to two conflicting values at the same time (which shouldn't happen), but what actually happens is that it's treated as a local call. Again, unsure if intended.

Maybe this should throw an error?

**Comment by elyisgreat** [comment] 2016-11-08 23:15
>Maybe this should throw an error?

Yeah, That should probably throw an error, however it also seems to happen when the types are different:
```
piano "pA": (tempo! 120) c d e f g
piano "pB": (quant! 30) e f g a b
```
 This case should create no conflict, however the same bug happens. 

>I think what you're describing is the behavior many users might expect, but from an implementation perspective, I think it's doing what it makes sense for it to do.

Agreed. As long as it's clearly outlined in the docs, it should work as intended, as it is more consistent from an implementation perspective. I am going to retitle the issue to focus on the other bug.

**Comment by daveyarwood** [comment] 2016-11-08 23:55
One key thing to note is that global attributes only act going _forward_ in the score. So, in the case of your example:

```
piano "pA": (tempo! 120) c d e f g
piano "pB": (quant! 30) e f g a b
```

Tempo 120 is applied to both pianos, but quantization 30 only applies to the second piano. This is why it seems like a "local" attribute change. It is in fact a global change, but it only applies to the second piano and any other instrument that you create after that.

**Comment by elyisgreat** [comment] 2016-11-09 01:07
That seems unintuitive to me. I would expect global attribute calls to apply to *all* instruments in the score from the time of the call, regardless of the order that the instruments are called in.

**Comment by daveyarwood** [comment] 2016-11-09 02:30
I'll have to think about this. I agree with you about the expected behavior, but I think there is a conflict with the way Alda works.

One nice property of the way Alda evaluates scores is that each line of a score entered into the Alda REPL sounds the same as it does when the score is played as a whole.

For example, if you enter the following two lines into the REPL:

```
> piano "pA": (tempo! 120) c d e f g
> piano "pB": (quant! 30) e f g a b
```

The `(quant! 30)` does not apply to the first line because we can't predict the future -- we have no way of knowing, at that point, that another instrument is going to apply a global attribute after we're done with the current instrument.

So after you enter those two lines and then enter `:play` into the REPL to hear the entire score, it should sound exactly the same, only the two parts will be in sync now.

If we make the change you're proposing, we break that property of Alda.

On the other hand, maybe that's not a big deal. Will have to think some more about this.

**Comment by elyisgreat** [comment] 2016-11-09 21:24
I actually never knew that this this was a property! Cool! While it is very philosophically satisfying, I do not think it is a strictly necessary property.  A good compromise could be to display a warning whenever this happens. Although I should mention again we will probably need a review of the scenarios and attribute-setting rules.

**Comment by daveyarwood** [comment] 2016-11-09 22:02
This would be a very difficult change to make -- the score evaluation logic we have now really depends on being able to determine the length of a note, in milliseconds, as the score is being evaluated from top to bottom.

If we wanted to change it, I would say the way to do it would be to defer calculating the duration in milliseconds until the moment you want to play the score. Then we would go through all the notes in the score a second time (with full knowledge of all the global attributes) and determine the durations in ms, based on whatever the tempo is at that moment in the score.

I'm a bit hesitant to do this, not only because of the philosophical property I mentioned above, but also because it would have some impact on performance. The performance impact could be negligible, but I'd still like to avoid it if we can. For the sake of simplicity, I'd really prefer for Alda scores to be evaluated in a single pass-through.

**Comment by elyisgreat** [comment] 2016-11-09 22:20
I suppose so, although what irritates me is that global attribute sets are only truly global if they are initiated at the beginning of the score or if initiated in the first instrument called. A nice example is with this code:

```
piano "pA": c d e f g
piano "pB": e f (tempo! 240) g a b
```

One would intuitively expect that the global attribute set here applies to all instruments at that time. However because the second piano hasn't been evaluated yet, the first piano doesn't have the attribute set. 

It gets even weirder with something like this though

```
piano "pA":
piano "pB": e f (tempo! 240) g a b
pA: c d e f g
```

which actually *does* play properly, since the second piano called is actually the instrument preceding the first piano in the code definitions.

The key here is this: Global attribute setting is more intuitive to think of as applying *from this point in the score going forward* as opposed to *from this point in the code going forward*. I don't know how one would get around the evaluation issue, though.

**Comment by daveyarwood** [comment] 2016-11-09 23:08
Right, I definitely agree with you. Let's keep this issue open for now.
Maybe somebody will have some insight about how to make this work the way
we want it to, but in a way that won't be tough to implement or have
undesirable performance implications.

**Comment by daveyarwood** [comment] 2016-11-23 23:55
Moved to https://github.com/alda-lang/alda-core/issues/24.

**Closed by daveyarwood** 2016-11-23 23:55 UTC
